<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
  <Description>A very simple extention to OakIdeas.GenericRepository that adds support for EF Core</Description>
  <PackageTags>repositorypattern, repository, data, EntityFrameworkCore</PackageTags>
  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  <PackageReleaseNotes>      
    - EntityFrameworkCore Repository      
  </PackageReleaseNotes>
  <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  <WarningsAsErrors>$(WarningsNotAsErrors);NU1605;SYSLIB0011</WarningsAsErrors>
</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OakIdeas.GenericRepository\OakIdeas.GenericRepository.csproj" />
  </ItemGroup>

</Project>
