<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>A very simple and generic implementation of the repository pattern for CRUD operations.</Description>
    <PackageTags>repositorypattern, repository, data</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageReleaseNotes>- Generic interface
- EntityBase
- Memory Repository (Dictionary based)</PackageReleaseNotes>
    <Title>OakIdeas Generic Repository</Title>
  </PropertyGroup>

  <PropertyGroup>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors>$(WarningsNotAsErrors);NU1605;SYSLIB0011</WarningsAsErrors>    
  </PropertyGroup>

 

  <ItemGroup>
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.3" />
  </ItemGroup>

</Project>
